### PR TITLE
docs: add a getting started and sources guide

### PR DESCRIPTION
**Pull request by qgolsteyn**
This breaks the README into a Getting Started and How to create a source guide. I expanded the How to create a source document to cover the latest approach we are currently taking for scraping.

### CODE REVIEW

**Comment by lazd** [comment]
Hmm, this looks fine, but I think the contributing stuff should go in `/Contributing.md`? https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Comment by jzohrab** [comment]
Hi @qgolsteyn, I have a README change I'd like to make, but this branch should go in first.  I'll resolve the conflicts in a new branch and will open a new PR, referencing this one.

@lazd, I agree it should go into `contributing.md`, but I won't make that change in my new branch, that can be a later PR which I can do if needed. :-)

**Comment by jzohrab** [comment]
Hi @qgolsteyn and @lazd , I've opened the new PR to move things over, this PR can be closed (@qgolsteyn , everything should be good with the docs, but you might want to do a last check in that PR).  Thanks! jz

**Comment by qgolsteyn** [comment]
Closed in favour of #395

**Pull request closed without merging**
