### PR TITLE
First go at automating deployment

### LINKED ISSUE #5: Automatic daily deployment
Data should be deployed daily at 9PM PST.

### PR DESCRIPTION
**Pull request by qgolsteyn**
This PR adds a Github Action to deploy the website every day at 9PM PST. It builds the CSV data and site, and deploys it on Github Pages.

Closes #5 

**Known issues**
- Not linked to releases, but probably should. This could be added with this PR.
- Fails if we disable TLS checks

### CODE REVIEW

**Comment by lazd** [comment]
Interesting that it fails with `--insecure-http-parser`... That's required to hit some of these sites since their certs are questionable.

And yeah JHU data breaks daily, so we just have to delay auto deployment until it's unbroken...

**Comment by lazd** [comment]
Interesting that it fails with `--insecure-http-parser`... That's required to hit some of these sites since their certs are questionable.

And yeah JHU data breaks daily, so we just have to delay auto deployment until it's unbroken...

Great work so far!

**Comment by qgolsteyn** [comment]
`--insecure-http-parser` works fine actually, so disabling TLS checks might be the only restriction imposed by Github Actions

**Comment by qgolsteyn** [comment]
Happy to hear feedback on this PR

**Comment by qgolsteyn** [comment]
I added an additional step to push the cache submodule following deployment. Can't test it fully as I don't have permission to push to that repo, but it should theoretically work.

**Comment by lazd** [comment]
@qgolsteyn I added you to the cache repo, please test and let me know if this is good to go!

**Comment by qgolsteyn** [comment]
Will do! Working on other things for the moment, but will get to it in a few hours

**Comment by qgolsteyn** [comment]
Moved to using tags on master as the trigger mechanism. This would allow us to deploy when we create a new release.

**Pull request merged**
