### PR TITLE
Add testing docs

### PR DESCRIPTION
**Pull request by jzohrab**
This PR builds on #395 

* Docs from @HerbCaudill in https://github.com/lazd/coronadatascraper/pull/345
* Add note on how to run unit tests

Second PR for issue #394

### CODE REVIEW

**Comment by qgolsteyn** [comment]
I merged #395 to keep moving on this topic.

**Comment by jzohrab** [comment]
Thanks very much @qgolsteyn.  This shouldn't have conflicts, but I'll sort that out on this same branch right now.

**Comment by jzohrab** [comment]
Updated, thank you again!

**Comment by qgolsteyn** [comment]
Good stuff!

**Pull request merged**
