### PR TITLE
Calculate ratings for datasources based on objective criteria

### LINKED ISSUE #82: Ratings for data sources
Scrapers should get a objective rating based on:

* ease of machine readability
* the completeness of available data
* timelines of updates
* consistency

We should advertise these ratings and actively point to them when reaching out to government department to demand better data.

### PR DESCRIPTION
**Pull request by lazd**
Closes #82 

This PR adds rating calculation based on available fields, data type, encryption, whether we have to access it headless, and whether it has time series data. The maximum rating is 1.

In addition, it uses the calculated rating to break ties when deduping data that has identical priorities.

### CODE REVIEW

**Comment by lazd** [comment]
@jbencina thoughts?

**Comment by jbencina** [comment]
I think this is a good first iteration. The values make intuitive sense and we're adding some objectivity to the process. We should just be careful to interpret this as the literal quality of how the data is pulled, vs. whether the source itself is credible or not.

**Comment by qgolsteyn** [comment]
Looks great! I would suggest moving the ratings to a separate `.json` or `.js` file at the top of the project, so we can easily view/edit these ratings, and import them in the function.

**Comment by lazd** [comment]
@qgolsteyn That's an excellent idea. They should probably be included in `report.json`!

**Comment by qgolsteyn** [comment]
That would be nice! Maybe (although maybe another PR) include a list of scrappers that were dropped due to a better source being present?

#87 to track that thought

**Comment by lazd** [comment]
@qgolsteyn agreed, let's report in another PR. Do you think this is ready to merge?

**Comment by qgolsteyn** [comment]
Yes, LGTM. Go for it 🚀

**Pull request merged**
