### PR TITLE
Sonoma,CA has been broken and returning 0 for awhile

### PR DESCRIPTION
**Pull request by chunder**

### CODE REVIEW

**Comment by lazd** [comment]
Let's make a `DeprecatedError` class in `src/shared/lib/errors.js` and throw an instance of that:

```
export class DeprecatedError extends Error {
  constructor(message) {
    super(message);
    this.name = "DeprecatedError";
  }
}
```

Then, in the scraper reports, we can do `if (err instanceof DeprecatedError) { doNothing(); }`

@qgolsteyn @camjc ?

**Comment by camjc** [comment]
In a PR I just did I returned an empty object. Good to have a standard way of doing this.

**Comment by camjc** [comment]
Yup, turns out an empty object still reports. Dang. Let’s do your approach.

**Comment by lazd** [comment]
We'll go ahead and close this one, thanks!

**Pull request closed without merging**
