### PR TITLE
feat: Use WayBack machine as fallback to missing cache

### PR DESCRIPTION
**Pull request by qgolsteyn**
If we try to access a resource that doesn't exit currently, or for which we don't have cache for, we try to fetch from the Wayback machine as an alternative. Still needs more testing.

### CODE REVIEW

**Comment by lazd** [comment]
@qgolsteyn I already started this work in: https://github.com/lazd/coronadatascraper/tree/wayback

Can you review what I had done previously and make sure there isn't anything I did that you're missing?

**Comment by camjc** [comment]
This feature would provide a lot of value. Let me know if theres anything I can do to help out.

**Comment by lazd** [comment]
@qgolsteyn let me know if you found anything in my branch that's missing here, otherwise we should continue to hack on this branch!

**Comment by lazd** [comment]
@qgolsteyn why close?

**Pull request closed without merging**
