### PR TITLE
county level data for Germany

### PR DESCRIPTION
**Pull request by Wikunia**
See #79 
Currently I have overwritten the old one but I should probably create a new scraper. Maybe @lazd can tell me how to do that the best way. 

**Edit:**
Additionally I don't know whether the counties/states should be translated into English.

### CODE REVIEW

**Comment by Wikunia** [comment]
Timeseries data in:
https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0
But I don't know how to back integrate them in the scraper

**Comment by jgehrcke** [comment]
Hey @Wikunia! Thanks for the work, in which we overlap a little bit and should coordinate ourselves :) I have left a comment here: https://github.com/lazd/coronadatascraper/issues/79#issuecomment-601744982

**Comment by lazd** [comment]
@jgehrcke and @Wikunia let me know which PR to merge!

**Comment by Wikunia** [comment]
@lazd you can merge the one by @jgehrcke

**Comment by lazd** [comment]
@Wikunia thank you!

**Pull request closed without merging**
