### PR TITLE
Ohio fix

### PR DESCRIPTION
**Pull request by SteveWallace**
updates Ohio url to new one

### CODE REVIEW

**Comment by lazd** [comment]
Seems like both URLs  work, any reason to switch?

Note that we'll need to use the old URL for dates < 2020-3-15. See other scrapers for examples on how do to that.

**Comment by SteveWallace** [comment]
They changed the page between when I did this and now!

**Comment by lazd** [comment]
@SteveWallace looks like this might be needed after all, Ohio stopped working and the old URL has a note that the info moved. Can you look into it?

**Comment by SteveWallace** [comment]
fixed in other PR

**Pull request closed without merging**
