### PR TITLE
Added county level scraper for ND, USA; added cheerio-tableparser dep…

### PR DESCRIPTION
**Pull request by chunder**
…endency

### CODE REVIEW

**Comment by lazd** [comment]
https://www.npmjs.com/package/cheerio-tableparser looks super powerful when dealing with `colspan` and `rowspan`. @ryanblock any issues with bundle size?

**Comment by lazd** [comment]
Nice!

**Comment by lazd** [comment]
Hmm, getting 0 cases for ND and an error:

```
  ❌ Error processing ND, USA:  TypeError: Cannot read property 'replace' of undefined
    at Proxy.string (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/shared/lib/parse.js:42:6)
    at Object.scraper (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/shared/scrapers/USA/ND/index.js:104:41)
    at async runScrapers (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/events/crawler/scrape-data/run-scraper.js:103:38)
    at async generate (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/shared/index.js:32:18)
    at async generateTimeseries (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/shared/timeseries.js:193:18)
```

**Comment by lazd** [comment]
RI issues too:
```
  ❌ Error processing RI, USA:  Error: Unknown headers in html table
    at Object.2020-3-26 (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/shared/scrapers/USA/RI/index.js:132:15)
    at async runScrapers (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/events/crawler/scrape-data/run-scraper.js:103:38)
    at async generate (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/shared/index.js:32:18)
    at async generateTimeseries (/Volumes/lazdRAID/Users/lazdHome/repos/coronavirus-data-sources/scraper/src/shared/timeseries.js:193:18)
```

**Comment by chunder** [comment]
RI works for me. ND blows up like you say. Let me look at it.

**Comment by lazd** [comment]
Thank you @chunder! I'll clear cache for RI, was getting these columns:
```
Age Group
Rhode Island COVID-19 patients by age:
```

**Comment by chunder** [comment]
Ok, I'm done adding stuff to this PR.

**Pull request merged**
