### PR TITLE
Add .catch to fetch (new KS, USA scraper)

### PR DESCRIPTION
**Pull request by ndom91**
So that the entire process doesn't get killed

### CODE REVIEW

**Comment by lazd** [comment]
@qgolsteyn was looking at fixing this for everything using `domain`. We already catch outside of this, so it shouldn't hose the whole process. Right now, only socket errors can take it out, for some reason...

**Comment by ndom91** [comment]
@lazd for some reason this does hose the whole process though unfortunately:

image

**Comment by lazd** [comment]
Yeah, that's exactly the error we were talking about... Seems like throwing the catch on the promise is a potential solution then too. @qgolsteyn?

**Comment by qgolsteyn** [comment]
Yes, I just tested this on my machine. We essentially need to catch the error, and avoid throwing again or it will crash the whole process.

**Comment by qgolsteyn** [comment]
We should change the `fetch` function directly. That way, all scrapers will get the fix. Will close this PR once I have a global fix.

**Comment by qgolsteyn** [comment]
Closing in favour of #321

**Pull request closed without merging**
