### PR TITLE
VA Scraper

### PR DESCRIPTION
**Pull request by aed3**

### CODE REVIEW

**Comment by qgolsteyn** [comment]
Amazing work! Awesome you managed to get data out of Tableau!

**Comment by qgolsteyn** [comment]
First, awesome work! Really cool that you managed to parse a Tableau PDF. I was about to merge and saw that you are using `pdf-parse`. I'm wondering if we could use the PDF scraper already implemented to avoid adding another dependency. Happy to help do the refactoring.

**Comment by aed3** [comment]
Thanks! I tried using the original pdf scraper, but the output didn't give something I could reliably use since there was no way of knowing where a number ended. However, it seems like the output of the original pdf parser changed and I could probably use it now. Will get started on that.

**Comment by qgolsteyn** [comment]
Alright! Feel free to ask questions here or ping me on Slack if you need anything!

**Comment by aed3** [comment]
Ok, I fixed it and will make a new pull request now.

**Pull request closed without merging**
